export const CREATE_TODO = 'CREATE_TODO';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const CREATE_TODO_ERROR = 'CREATE_TODO_ERROR';

export const INIT_TODO = 'INIT_TODO';
export const INIT_TODO_SUCCESS = 'INIT_TODO_SUCCESS';
export const INIT_TODO_ERROR = 'INIT_TODO_ERROR';

export const EDIT_TODO = 'EDIT_TODO';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
export const EDIT_TODO_ERROR = 'EDIT_TODO_ERROR';

export const TOGGLE_TODO = 'TOGGLE_TODO';
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS';
export const TOGGLE_TODO_ERROR = 'TOGGLE_TODO_ERROR';
